In [1]:
import numpy as np

In [36]:
def generate_random_matrix(N):
    M = np.zeros((N,N)) # empty matrix of size N
    
    # diagonal
    P = np.random.poisson(lam=1, size=N)
    Y = P - 1
    for i in range(N):
        M[i,i]=Y[i] / np.sqrt(N)

    # off diagonal
    for i in range(N):
        for j in range(i+1, N):
            B = np.random.binomial(n=10, p=0.5)
            Z = (B - 5) / np.sqrt(N)

            M[i,j] = Z
            M[j,i] = Z

    return M

matrix = generate_random_matrix(4)
print(matrix)
            

[[ 0.  -1.   0.5 -1. ]
 [-1.  -0.5 -1.5 -0.5]
 [ 0.5 -1.5  0.   0.5]
 [-1.  -0.5  0.5 -0.5]]


In [10]:
def find_trace(matrix):
    return np.trace(matrix)

print(find_trace(matrix))

0.0


In [42]:
k = 2
N = 4
runs = 1000

results = np.zeros((runs))

for r in range(runs):
    matrix = generate_random_matrix(N)
    moment = matrix @ matrix
    trace = find_trace(moment)
    results[r] = trace

answer = np.average(results) / N
print(answer)


2.2040625
